### ISSUE TITLE
module_generator config does not seem to apply

### ISSUE THREAD

**Issue by stephendpmurphy** [ThrowTheSwitch/Ceedling#645]
Hi there :wave: I am attempting to use the module_generator config to create templates for my .c and .h files generated (We specifically want to have the files preoloaded without licensing as well as Doxygen headers). I am following the documentation [here](https://github.com/ThrowTheSwitch/Ceedling/blob/master/docs/CeedlingPacket.md#module-generator)

My ceedling versioning is here:
```console
Ceedling:: 0.31.1
Unity:: 2.5.4
CMock:: 2.5.4
CException:: 1.3.3
```

The issue: I've tried applying config in two ways; Using the ```:boilerplates:``` and ```:includes:``` config options as well as passing a template source file using ```:boilerplate_files:```. **Neither of these have an effect on the files generated - The .c file is always blank with a single include for its header file at the top**. Am I missing something? Below is my .yml config for the module_generator as well as enabling the plugin.

Module Generator Config
```yml
:module_generator:
  :boilerplate_files:
    :src: 'template\src_boilerplate.txt'
```
Boilerplate file
```c
// This is a boilerplate
#include "error.h"
#include "version.h"

// Macros

// Variables

// Functions
```
Plugins Config
```yml
:plugins:
  :load_paths:
    - "#{Ceedling.load_path}"
  :enabled:
    - xml_tests_report
    - stdout_pretty_tests_report
    - module_generator
    - gcov
```

**Comment by stephendpmurphy** [comment]
Might as well include my whole config file
```yml
---

# Notes:
# Sample project C code is not presently written to produce a release artifact.
# As such, release build options are disabled.
# This sample, therefore, only demonstrates running a collection of unit tests.

:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :build_root: build
#  :release_build: TRUE
  :test_file_prefix: test_
  :which_ceedling: gem
  :ceedling_version: 0.31.0
  :default_tasks:
    - test:all

#:test_build:
#  :use_assembly: TRUE

#:release_build:
#  :output: MyApp.out
#  :use_assembly: FALSE

:environment:

:extension:
  :executable: .out

:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - src/**
    - vendor/**

  :support:
    - test/support
  :libraries: []

:defines:
  # in order to add common defines:
  #  1) remove the trailing [] from the :common: section
  #  2) add entries to the :common: section (e.g. :test: has TEST defined)
  :common: &common_defines
    - CPU_DEFINE_PN

  :test:
    - *common_defines
    - TEST
  :test_preprocess:
    - *common_defines
    - TEST

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    int8:     INT8
    bool:     UINT8

# Add -gcov to the plugins list to make sure of the gcov plugin
# You will need to have gcov and gcovr both installed to make it work.
# For more information on these options, see docs in plugins/gcov
:gcov:
  :utilities:
    - gcovr
  :reports:
    - HtmlBasic
    - HtmlDetailed
    - Xml
  :xml_report: true
  :gcovr:
    :html_medium_threshold: 75
    :html_high_threshold: 90

#:tools:
# Ceedling defaults to using gcc for compiling, linking, etc.
# As [:tools] is blank, gcc will be used (so long as it's in your system path)
# See documentation to configure a given toolchain for use

# LIBRARIES
# These libraries are automatically injected into the build process. Those specified as
# common will be used in all types of builds. Otherwise, libraries can be injected in just
# tests or releases. These options are MERGED with the options in supplemental yaml files.
:libraries:
  :placement: :end
  :flag: "-l${1}"
  :path_flag: "-L ${1}"
  :system: []    # for example, you might list 'm' to grab the math library
  :test: []
  :release: []

:module_generator:
  :boilerplate_files:
    :src: 'template\src_boilerplate.txt'

:plugins:
  :load_paths:
    - "#{Ceedling.load_path}"
  :enabled:
    - xml_tests_report
    - stdout_pretty_tests_report
    - module_generator
    - gcov
...
```
